version: '3'
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - /Users/nagaimidori/git/prometheustest/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - /Users/nagaimidori/git/prometheustest/prometheus/alert.rules:/etc/prometheus/alert.rules
    ports:
      - 9090:9090
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - /Users/nagaimidori/git/prometheustest/grafana/grafana.env:/etc/grafana/grafana.emv
    env_file:
      - /Users/nagaimidori/git/prometheustest/grafana/grafana.env
  node-exporter:
    image: quay.io/prometheus/node-exporter
    container_name: node-exporter
    ports:
      - '9100:9100'
    volumes:
      - /proc:/host/proc
      - /sys:/host/sys
      - /:/rootfss
  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    volumes:
      - /Users/nagaimidori/git/prometheustest/alertmanager/config.yml:/etc/alertmanager/config.yml
    command: "--config.file=/etc/alertmanager/config.yml"
    ports:
      - 9093:9093
    restart: always
